version: '2.1'
services:
    postgres:
        # $ PGPASSWORD=unitedmaster psql -h "localhost" -p 54322 -U metadatamaster metadata_management
        image: postgres:9.6
        ports:
            - 54322:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=modou
            - PGDATA=/var/lib/postgresql/data
        volumes:
            - ./pgdata:/var/lib/postgresql/data
            - ./db:/db/
